

version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      
  build:
    commands:
     
      - find . -type f -name "Dockerfile" -print -exec sed -i "s/FROM .*/FROM $DOCKER_IMAGE/" {} \; 
      #- sed -i '' -e 's/FROM .*/FROM $DOCKER_IMAGE/' ./Dockerfile
      #- sed -i Dockerfile -e "s/FROM .*/FROM $DOCKER_IMAGE/" Dockerfile
      - cat Dockerfile
   
