

version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      
  build:
    commands:
     
      - sed -in "" "s/FROM .*/FROM $DOCKER_IMAGE/" Dockerfile
      - cat Dockerfile
   
